name: Hourly Log File

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour, at the start of the hour (UTC)
    - cron: '0 0 * * *'  # Runs at midnight UTC to clear the file

jobs:
  log-time:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Log date, time, and day to a text file every hour
      - name: Log current date, time, and day
        if: github.event.schedule.cron == '0 * * * *'  # This step runs only every hour
        run: |
          # Get current date, time, and day (in UTC)
          DATE=$(date -u "+%Y-%m-%d")
          TIME=$(date -u "+%H:%M:%S")
          DAY=$(date -u "+%A")
          
          # Create or append to the log file
          echo "$DATE $TIME - $DAY" >> log.txt
          
          # Commit the new log entry to the repository
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git remote set-url origin https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com/${{ github.repository }}
          git add log.txt
          git commit -m "Add log entry for $DATE $TIME" || echo "No changes"
          git push

      # Step 3: Clear the log file at the end of the day (midnight UTC)
      - name: Clear log file at midnight
        if: github.event.schedule.cron == '0 0 * * *'  # This step runs only at midnight UTC
        run: |
          # Clear the content of the log file
          > log.txt
          
          # Commit the cleared log file to the repository
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git remote set-url origin https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com/${{ github.repository }}
          git add log.txt
          git commit -m "Clear log file for the new day" || echo "No changes"
          git push
